@unsplash_key=VITE_UNSPLASH_ACCESS_KEY

### Unsplash API - Random Photos (header)
GET https://api.unsplash.com/photos/random?count=50
Authorization: Client-ID {{unsplash_key}}
Accept-Version: v1

### Unsplash API - Random Photos (fallback query param)
GET https://api.unsplash.com/photos/random?count=4&client_id={{unsplash_key}}
Accept-Version: v1

### Unsplash API - Search Photos
GET https://api.unsplash.com/search/photos?query=city&per_page=5&page=1
Authorization: Client-ID {{unsplash_key}}
Accept-Version: v1

### Unsplash API - Global Statistics
GET https://api.unsplash.com/stats/total
Authorization: Client-ID {{unsplash_key}}
Accept-Version: v1